### ISSUE TITLE
Source version with laravel mix

### ISSUE THREAD

**Issue by MichalKrakow** [ecomfe/vue-echarts#275]
Hey,
what if editing webpack config is out of table and one have to deal with laravel mix instead.

How to implement [this](https://github.com/ecomfe/vue-echarts#%EF%B8%8F-heads-up) then?

**Comment by Justineo** [comment]
I'm not familiar with Laravel mix personally. I found there is somethin called `mix.babel()` in [its docs](https://laravel.com/docs/5.6/mix) that can be used to add paths to be transpiled. Or you can try using the bundled version.
---
Please DO READ the issue template and do as instructed otherwise the issue will be closed directly.

**Comment by MichalKrakow** [comment]
Sorry for missing the issue template,
since the thred is already here i'll put the solution
```
// webpack.mix.js
mix.webpackConfig({
	module: {
        rules: [
            {
                test: /\.jsx?$/,
                include: [
                	path.resolve('node_modules/vue-echarts'),
                        path.resolve('node_modules/resize-detector')
                ],
                use: [
                    {
                        loader: 'babel-loader',
                        options: Config.babel()
                    }
                ]
            }
        ]
    }
});
```
