### ISSUE TITLE
ES modules to reduce bundle size

### ISSUE THREAD

**Issue by ThomasKientz** [ecomfe/vue-echarts#345]
I don't get it, how importing more modules (`import 'echarts/lib/...`) can reduce the bundle size comparing to import only `import ECharts from 'vue-echarts' ` ?  

```
import Vue from 'vue'
import ECharts from 'vue-echarts' // refers to components/ECharts.vue in webpack

// import ECharts modules manually to reduce bundle size
import 'echarts/lib/chart/bar'
import 'echarts/lib/component/tooltip'
```

**Comment by Techiu** [comment]
> import ECharts from 'vue-echarts'
this operation just import the vue-echarts components, but it won't work without original echarts package.

so, you need to import echarts package.
whether the whole package

> import 'echarts'

 or part of it as you wish.

> import 'echarts/lib/chart/bar'

> import 'echarts/lib/component/tooltip'

**Comment by Justineo** [comment]
@ThomasKientz 



> I don't get it, how importing more modules (`import 'echarts/lib/...`) can reduce the bundle size comparing to import only `import ECharts from 'vue-echarts' ` ?

`vue-echarts` points to `vue-echarts/components/ECharts.vue` because we've specifed a `module` field in our `package.json`:

https://github.com/ecomfe/vue-echarts/blob/daf96f1437a67d4c2cf9dad780341bec0859c0d1/package.json#L6

And in the SFC, we only imported `echarts/lib/echarts` which is only the core part of ECharts and you need to manually import parts you are gonna use like:

```js
import 'echarts/lib/chart/bar'
```

But if you import `vue-echarts/dist/vue-echarts`, it will include the bundled version of ECharts with some common charts and components. And this will likely to give you unnecessary charts and components.

Hope this helps :)

**Comment by ThomasKientz** [comment]
Thanks a lot :)

I was importing an old `'vue-echarts-v3/src/full.js'` in old component, so I get messed up..

However, I have forked the demo and commented those lines :

```
import qs from "qs";
import ECharts from "../components/ECharts.vue";
// import 'echarts/lib/chart/bar'
// import 'echarts/lib/chart/line'
// import 'echarts/lib/chart/pie'
// import 'echarts/lib/chart/map'
// import 'echarts/lib/chart/radar'
// import 'echarts/lib/chart/scatter'
// import 'echarts/lib/chart/effectScatter'
// import 'echarts/lib/component/tooltip'
// import 'echarts/lib/component/polar'
// import 'echarts/lib/component/geo'
// import 'echarts/lib/component/legend'
// import 'echarts/lib/component/title'
// import 'echarts/lib/component/visualMap'
// import 'echarts/lib/component/dataset'
```
And graphs still show up after `npm run serve`, don't understand why !

**Comment by Justineo** [comment]
That's due to a bug of ECharts. The built-in theme module (`echarts/theme/dark`) imports the whole `echarts` package.
