### ISSUE TITLE
Method to set english as the default language?

### ISSUE THREAD

**Issue by BrianGilbert** [ecomfe/vue-echarts#430]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
ECharts currently has no way to set the language at runtime, it needs to be selected at the build stage, reference:
https://github.com/apache/incubator-echarts/issues/7451#issuecomment-442947610

I found the following note on the echarts repo that may give a way to set it, but I can't figure where this would be added when using vue-echarts:
https://github.com/apache/incubator-echarts/issues/12037#issuecomment-574593683

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)
- [x] following the nuxt v2 instructions in the readme https://github.com/ecomfe/vue-echarts#using-with-nuxtjs

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
4.7.0

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
You can try add a [webpack `alias`](https://webpack.js.org/configuration/resolve/#resolvealias) that map `echarts/lib/lang` to `echarts/lib/langEN`. See how to extend webpack config in Nuxt [here](https://nuxtjs.org/faq/extend-webpack).

**Comment by Decipher** [comment]
@Justineo 

Unfortunately, as the `vue-charts` module is importing from the source of `echarts` instead of the bundle, the only way that I can make an alias work is with the following, potentially dangerous code:

```
config.resolve.alias['../lang'] = path.resolve(__dirname, 'MYFILE')
```

It would be preferable if I didn't have to target the file so loosely, as it could have negative effects on unrelated code.

I have not dealt with webpack aliases before, so I may be missing something obvious, but thus far changing the language seems quite inaccessible.

**Comment by Decipher** [comment]
@Justineo Can this be re-opened, the solution is not viable for real world usage.

**Comment by Decipher** [comment]
@Justineo 

Based off my looking into this issue, it appears the main problem is that `vue-echarts` uses the source (`echarts/lib/echarts`) rather than the dist. However, this is still likely the preferred choice to reduce the size of the bundle.

There was/is also an issue with the dist version of the english translation, but @BrianGilbert has pushed a fix for this (https://github.com/apache/incubator-echarts/pull/12387). However, until there's a new release, this fix isn't overly helpful yet.

I'm not 100% certain what the best solution is at the moment, but my gut feeling is I'm either going to have to use a fork of `vue-echarts` and/or a fork of `echarts`.

Any thoughts on best to deal with this issue would be appreciated.

**Comment by BrianGilbert** [comment]
I think a lang config option in mainline echarts would be the best long term solution

**Comment by Justineo** [comment]
I'll discuss this with the ECharts team later and try to figure out a solution for this.

**Comment by Justineo** [comment]
Hi folks, it seems that they plan to provide better language support for `echarts@5` which will probably shipped around the end of June.

**Comment by stereokai** [comment]
@Justineo well, it's already July and `echarts@5` [nowhere near to being released](https://github.com/apache/incubator-echarts/projects/6)

Can we address this for now?

**Comment by dantimofte** [comment]
Hello, in case it helps someone until a  proper solution is released this is my workaround:
I added the following line in my cicd pipeline: 

mv node_modules/echarts/lib/langEN.js node_modules/echarts/lib/lang.js

**Comment by stereokai** [comment]
Thanks @dantimofte !

**Comment by Justineo** [comment]
ECharts 5 now supports [`registerLocale`](https://echarts.apache.org/en/api.html#echarts.registerLocale) at runtime. You can try to migrate to `vue-echarts@6` for ECharts 5 support.
