### ISSUE TITLE
echarts-gl Cannot use import statement outside a module 

### ISSUE THREAD

**Issue by Moxie1776** [ecomfe/vue-echarts#567]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [X] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。
I have checked it as far as I can figure out, this seems to be unique to vue-echarts with echarts-gl

### Vue version / Vue 版本

- [ ] Vue 3
- [X] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [X] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
echarts 5.1.2
echarts-gl 2.0.5
nuxt 2.15.7
vue-echarts 6.0.0-rc.6

## Reproduction link / 复现链接
https://codesandbox.io/s/vue-echarts-echarts-gl-import-error-zrkt0

I hope this is the correct place to submit this bug. Navigate to a bogus URL in the codesandbox browser, use the error screen to navigate back to the home page and this chart will render. On launch or refresh this error occurs.

**Comment by JLBlueDom** [comment]
Is there an option for paid support to get this fixed?

**Comment by Justineo** [comment]
This issue is a little complicated. After some investigation I found 3 related issues.

1. You need to add `claygl` to the `build.transpile` option in `nuxt.config.js`.
2. `echarts-gl` will choke on server side and I've made a PR to fix it: ecomfe/echarts-gl#422
3. The latest version of `vue-demi` seems to not play well with Nuxt and I don't know why yet: vueuse/vue-demi#90

So to make it work we need to wait for `echarts-gl` to release a new version (maybe @pissang can help) and use `vue-echarts@6.0.0-rc.6` (which depends on `vue-demi@0.9.1`) for now.

**Comment by Justineo** [comment]
Feel free to open up a new issue if the solution above doesn't work. Thanks for reporting.

**Comment by Moxie1776** [comment]
Thank you for working on this, I will test it out this morning.

**Comment by Moxie1776** [comment]
I did test this yesterday and I have confirmed that it is working. Thank you for your help on this.  Above a request had been asked about an option for paid support from time to time, is that an option?

**Comment by Justineo** [comment]
Unfortunately, there is no paid support at this time (nor do we have long-term plans).
