### ISSUE TITLE
Support ESM explicitly in package.json

### ISSUE THREAD

**Issue by ElmoArmy** [ecomfe/vue-echarts#601]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

Looks like the space and standards are moving towards ESM, it'd be cool if this library embraced that by switching to a package.json config that included these lines: 
```json
"type": "module",
  "exports": {
    ".": {
      "require": "./dist/index.cjs.js",
      "import": "./dist/index.esm.js",
      "types": "./dist/index.d.ts"
    }
  },
  ```
 As it stands I'm running into issues using this library as a native module. 
 
 Additional context about this issue:
-   https://v3.nuxtjs.org/concepts/esm/#what-kinds-of-problems-can-there-be
-   antfu/vite-ssg#201

**Comment by ElmoArmy** [comment]
Meh, this is a bad suggestion. I'll come back with a PR to change the build to explicitly name esm modules .mjs and cjs files .cjs.

**Comment by sheremet-va** [comment]
There is actually an issue in Vitest concerning this: https://github.com/vitest-dev/vitest/issues/1452 (basically, Vitest doesn't respect `module` field, because it's not part of Node resolution scheme, so it imports `cjs` entry - and even if it did, it would still fail, because Node considers your ESM entry a `cjs` file, more on that later).

> Meh, this is a bad suggestion as it would only support ESM. I'll come back with a PR to change the build to explicitly name esm modules .mjs and cjs files .cjs.

I have a [guide on how to support dual packaging](https://github.com/sheremet-va/dual-packaging) (it also explains why `exports` in your issue description is wrong)
