### ISSUE TITLE
allow use vm.$on to listense event

### ISSUE THREAD

**Issue by arika163** [ecomfe/vue-echarts#612]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

to write my chart componet like a dumb,I hope i can deal with events in a parent component and write something like below: 
```
childComponent.$refs.chart.$on('zr:click',() => { //do something })
```
but i find vm.$on never work

**Comment by Justineo** [comment]
This is because Vue ECharts is only listening to the events for which the user has provided event handlers declaratively (via `v-on`). If we want `vm.$on` to work we'll have to listen to every single event from `echarts` and `zrender` and emit them out again via Vue's event API, which is very wasteful. So I think this will be a wontfix.
