### ISSUE TITLE
Nuxt 3 Module

### ISSUE THREAD

**Issue by Celibioux** [ecomfe/vue-echarts#775]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

It would be nice to have a Nuxt 3 compatible Module with SSR maybe !?

**Comment by kingyue737** [comment]
https://echarts.apache.org/handbook/en/how-to/cross-platform/server#server-side-svg-rendering

> We also have to specify the height and width of the chart, so if your chart size needs to be responsive to the container, you may need to think about whether server-side rendering is appropriate for your scenario.

In my opinion, it seems that scenarios of SSR ECharts are limited since many users use `VueEcharts` with `autoresize` prop which does not work on the server side. We cannot know the size of the container in advance.

**Comment by kingyue737** [comment]
I write a Nuxt Module for ECharts with support of SSR. 

https://github.com/kingyue737/nuxt-echarts

docs: https://echarts.nuxt.dev

It's currently in active development. Any suggestion or issue reports  are very welcome.

**Comment by Justineo** [comment]
I'm closing this issue as @kingyue737 is working on a Nuxt Module for ECharts 👍. See the comment above.
